CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255),
    full_name VARCHAR(100),
    avatar_url VARCHAR(500),
    role ENUM('ROLE_USER','ROLE_ADMIN','ROLE_VIP') DEFAULT 'ROLE_USER',
    provider ENUM('LOCAL','GOOGLE','FACEBOOK') DEFAULT 'LOCAL',
    provider_id VARCHAR(255),
    is_active BOOLEAN DEFAULT TRUE,
    email_verified BOOLEAN DEFAULT FALSE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
